# Generated by Django 5.2.8 on 2025-11-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_fix_admin_user_fk'),
    ]

    operations = [
    ]
